### PR TITLE
Mixed Python + Rust package

### PR DESCRIPTION
**Pull request by douglasdavis**
This PR makes the Rust based extension module importable as `rfsspec.rfsspec`

### CODE REVIEW

**Comment by martindurant** [comment]
Copying out the draft PR from fsspec? 

This is good to be able to do testing. The original HTTPFileSystem has tests we could reuse, except that rfsspec doesn't pass on header values to the request yet.

**Comment by douglasdavis** [comment]
Just experimenting to allow being able to import pure Python objects from rfsspec as well, can now run e.g.
```python
import rfsspec.html
fs = rfsspec.http.HTTPFileSystem(...)
```

**Comment by douglasdavis** [comment]
> Copying out the draft PR from fsspec?

yep just copied from `fsspec.implementions.http_rust.py`

**Comment by martindurant** [comment]
I'll put this in and continue iterating, unless you have more you want to do.

**Comment by douglasdavis** [comment]
Nope that sounds good!

**Pull request merged**
